name: flutter
description: A framework for writing Flutter applications
homepage: https://github.com/dint-dev/server_side_flutter_fork

environment:
  sdk: ^3.10.0-0

dependencies:
  characters: ^1.3.0
  collection: ^1.17.0
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  vector_math: ^2.2.0

dev_dependencies:
  lints: ^6.0.0
